import type { IconFontName } from '@/assets/iconfont/registry/iconfont-names'

export const iconAliasMap = {
  'tool-edit-active': 'tool-edit',
  'tool-lock-active': 'tool-lock',
  'tool-copy-active': 'tool-copy',
  'tool-delete': 'trash',
  'tool-delete-active': 'trash',
  'chip-close-default': 'chip-close',
  'chip-close-active': 'chip-close',
  'chip-close-muted': 'chip-close',
  'card-star-outline': 'star-outline',
  'card-star-green': 'star-filled',
  'card-star-orange': 'star-filled',
  'asset-star-outline': 'star-outline',
  'asset-star-purple': 'star-filled',
  'asset-trash': 'trash',
  'card-delete': 'trash',
  'timeline-delete-default': 'trash',
  'topbar-home-active': 'topbar-home',
  'topbar-resource-active': 'topbar-resource',
  'topbar-voice-active': 'topbar-voice',
  'topbar-team-active': 'topbar-team',
  'topbar-system-active': 'topbar-system',
  'topbar-credit-cart-active': 'topbar-cart-default',
  'topbar-user-active': 'topbar-user',
  'topbar-user-defaults': 'topbar-user',
  'topbar-points-active': 'topbar-points',
  'timeline-upload-active': 'timeline-upload',
  'timeline-copy-active': 'timeline-copy',
  'timeline-delete-active': 'timeline-delete',
  'checkbox-unchecked': 'checkbox-checked',
} as const satisfies Partial<Record<string, IconFontName>>
